### ISSUE TITLE
Add link to this repo on AMO

### ISSUE THREAD

**Issue by Gitoffthelawn** [Fushko/font-contrast#14]
The AMO page (https://addons.mozilla.org/firefox/addon/font-contrast-fix/) for this extension is missing a link to this repo.  Could it be added?  Mozilla allows add-on devs to include a homepage and support URL on their extensions' AMO page.

**Comment by Fushko** [comment]
![immagine](https://user-images.githubusercontent.com/22770482/195048045-fb2cee51-61a0-450a-9ec4-408439528c9b.png)
It's there, what do you see?

**Comment by Gitoffthelawn** [comment]
You're absolutely correct.  However, the homepage and support URL links in the `More information` > `Add-on Links` section are missing.

For example, see that section for:  
https://addons.mozilla.org/firefox/addon/simple-tab-groups

Those links are especially important for accessibility devices such as screen readers.

**Comment by Fushko** [comment]
Added homepage and support site for the time being. Thank you.

**Comment by Gitoffthelawn** [comment]
Looks great.  You're welcome.  And thank *you*.
