### ISSUE TITLE
Don't include .git subdirectory in add-on

### ISSUE THREAD

**Issue by int-e** [Fushko/font-contrast#3]
The add-on available at https://addons.mozilla.org/en-US/firefox/addon/font-contrast-fix/ includes the `.git` subdirectory with full version history. That seems unnecessary.

(I actually looked inside the add-on because it seemed to be a bit too big for what it does. Without the `.git` directory it would be 1/4 the size.)

**Comment by Fushko** [comment]
I'll remove it from the next release. Thanks for pointing that out.

**Comment by Fushko** [comment]
.git directory has been removed from 1.5.9
